build_exe:
    script:
        - mkdir -p build
        - cd build
        - git clone git@gitlab.com:dmytro.bogovych/libraries.git
        - cmake -D PLATFORM_LIBS=libraries ../src
        - cmake --build .
        