build_exe:
    script:
        - mkdir -p build
        - cd build
        - git clone https://gitlab.com/dmytro.bogovych/libraries.git
        - cmake -D LIB_PLATFORM=libraries ../src
        - cmake --build .
        